name: Test

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add rustfmt
      - name: Toolchain info
        run: |
          rustc --version
          cargo --version --verbose
          cargo fmt --version
      - name: Format
        run: |
          cargo fmt
      - name: Diff check
        run: |
          test -z "$(git status -s)"

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
      - name: Toolchain info
        run: |
          rustc --version
          cargo --version --verbose
          cargo clippy --version
      - name: Clippy check
        run: |
          cargo clippy --all-features --all-targets

  test:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
      - name: Toolchain info
        run: |
          rustc --version
          cargo --version --verbose
          cargo llvm-cov --version
      - name: Test
        run: |
          cargo llvm-cov --all-features
